nfimage:
  registry: local
  repository: docker.io/openran/nr-ue         
  version: develop 
  pullPolicy: IfNotPresent
  
service:
  type: ClusterIP
  s1uPort: 2152
  s1cPort: 36412
  x2cPort: 36422 

config:
  timeZone: "Europe/Paris"
  rfSimulator: "172.17.0.11"    
  fullImsi: "208990100001121"       
  fullKey: "fec86ba6eb707ed08905757b1bb44b8f" 
  opc: "C42449363BBAD02B66D16BC975D77CC1"
  dnn: "openran"                    
  
resources:
  define: false
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
   cpu: 100m
   memory: 256Mi
   
   
   
   
   
   